// components/Layout.tsx
import { type ReactNode } from 'react';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Navbar from './navbar';
import Loading from './loading';

interface LayoutProps {
    children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
    const { status } = useSession();


    return (
        <>
            <Head>
                <title>PMA</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex min-h-screen flex-col bg-gradient-to-b from-[#ffffff] to-[#232323]'>
                {status == 'loading' && <Loading />}
                {status == 'authenticated' && <Navbar />}
                {children}
            </div>
        </>
    );
};

export default Layout;